version: '3'

services: 
  mysql-app:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: developers_crud
      MYSQL_ROOT_PASSWORD: root321
    networks: 
      - devs-crud-network

  backend-app:
    build: ./backend
    ports: 
      - "8000:80"
    networks: 
      - devs-crud-network
    depends_on: 
      - mysql-app

  frontend-app:
    build: ./frontend
    ports: 
      - "8080:8080"
    networks: 
      - devs-crud-network
    depends_on: 
      - backend-app

networks: 
  devs-crud-network:
    driver: bridge