version: '3.8'

services: 
  mysqldb:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_DATABASE: developers
      MYSQL_ROOT_PASSWORD: root321
    networks: 
      - devs-crud-network

  backend-app:
    build: ./backend
    ports: 
      - "8000:80"
    working_dir: "/usr/share/nginx"
    networks: 
      - devs-crud-network
    depends_on: 
      - mysqldb

  frontend-app:
    build: ./frontend
    ports: 
      - "8080:8080"
    networks: 
      - devs-crud-network

networks: 
  devs-crud-network:
    driver: bridge